import { Category, HeroSlide, Product, Vendor } from "@/types";

// ─────────────────────────────────────────
// VENDORS
// ─────────────────────────────────────────
export const vendors: Vendor[] = [
  {
    id: "v1",
    name: "NatureRoot Organics",
    slug: "natureroot-organics",
    logo: "https://api.dicebear.com/8.x/initials/svg?seed=NR&backgroundColor=A6D608&textColor=1E1E1E",
    banner: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&q=80",
    description: "Premium organic health supplements and natural wellness products sourced directly from nature.",
    rating: 4.8,
    reviewCount: 1234,
    productCount: 86,
    location: "Mumbai, Maharashtra",
    isVerified: true,
    isTopSeller: true,
    deliveryPerformance: 99,
    joinedDate: "2021-03-15",
    specialties: ["Organic Supplements", "Herbal Extracts", "Superfoods"],
  },
  {
    id: "v2",
    name: "VitaLife Labs",
    slug: "vitalife-labs",
    logo: "https://api.dicebear.com/8.x/initials/svg?seed=VL&backgroundColor=FF7A00&textColor=ffffff",
    banner: "https://images.unsplash.com/photo-1576671081837-49000212a370?w=800&q=80",
    description: "Science-backed vitamins, minerals, and nutraceuticals for optimal health performance.",
    rating: 4.6,
    reviewCount: 892,
    productCount: 62,
    location: "Bengaluru, Karnataka",
    isVerified: true,
    isTopSeller: true,
    deliveryPerformance: 97,
    joinedDate: "2020-07-20",
    specialties: ["Vitamins", "Minerals", "Protein Supplements"],
  },
  {
    id: "v3",
    name: "AyurVeda Plus",
    slug: "ayurveda-plus",
    logo: "https://api.dicebear.com/8.x/initials/svg?seed=AP&backgroundColor=2CA7A0&textColor=ffffff",
    banner: "https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=800&q=80",
    description: "Authentic Ayurvedic formulations rooted in 5000 years of traditional Indian medicine.",
    rating: 4.7,
    reviewCount: 567,
    productCount: 44,
    location: "Pune, Maharashtra",
    isVerified: true,
    isTopSeller: false,
    deliveryPerformance: 98,
    joinedDate: "2022-01-10",
    specialties: ["Ayurveda", "Traditional Medicine", "Herbal Care"],
  },
  {
    id: "v4",
    name: "FitFuel Nutrition",
    slug: "fitfuel-nutrition",
    logo: "https://api.dicebear.com/8.x/initials/svg?seed=FF&backgroundColor=1E1E1E&textColor=A6D608",
    banner: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80",
    description: "Sports nutrition and fitness supplements to fuel your performance and recovery.",
    rating: 4.5,
    reviewCount: 1102,
    productCount: 78,
    location: "Delhi, NCR",
    isVerified: true,
    isTopSeller: true,
    deliveryPerformance: 96,
    joinedDate: "2019-11-05",
    specialties: ["Pre-Workout", "Protein", "Recovery"],
  },
  {
    id: "v5",
    name: "PureSkin Wellness",
    slug: "pureskin-wellness",
    logo: "https://api.dicebear.com/8.x/initials/svg?seed=PS&backgroundColor=8ab506&textColor=ffffff",
    banner: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800&q=80",
    description: "Natural skincare and personal care products crafted with plant-based ingredients.",
    rating: 4.9,
    reviewCount: 743,
    productCount: 35,
    location: "Chennai, Tamil Nadu",
    isVerified: true,
    isTopSeller: false,
    deliveryPerformance: 99,
    joinedDate: "2021-08-22",
    specialties: ["Skincare", "Natural Beauty", "Wellness"],
  },
];

// ─────────────────────────────────────────
// CATEGORIES
// ─────────────────────────────────────────
export const categories: Category[] = [
  {
    id: "c1",
    name: "Vitamins & Supplements",
    slug: "vitamins-supplements",
    icon: "💊",
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&q=80",
    productCount: 248,
    color: "#A6D608",
    gradient: "linear-gradient(135deg, #A6D608, #c5f020)",
    subcategories: ["Multivitamins", "D3 & K2", "Omega 3", "Calcium"],
  },
  {
    id: "c2",
    name: "Herbal & Ayurvedic",
    slug: "herbal-ayurvedic",
    icon: "🌿",
    image: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=400&q=80",
    productCount: 186,
    color: "#2CA7A0",
    gradient: "linear-gradient(135deg, #2CA7A0, #35c9c1)",
    subcategories: ["Ashwagandha", "Triphala", "Brahmi", "Curcumin"],
  },
  {
    id: "c3",
    name: "Sports Nutrition",
    slug: "sports-nutrition",
    icon: "💪",
    image: "https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=400&q=80",
    productCount: 154,
    color: "#FF7A00",
    gradient: "linear-gradient(135deg, #FF7A00, #ff9a40)",
    subcategories: ["Whey Protein", "BCAAs", "Creatine", "Pre-workout"],
  },
  {
    id: "c4",
    name: "Organic Foods",
    slug: "organic-foods",
    icon: "🥗",
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&q=80",
    productCount: 213,
    color: "#22c55e",
    gradient: "linear-gradient(135deg, #22c55e, #4ade80)",
    subcategories: ["Superfoods", "Nuts & Seeds", "Grains", "Honey"],
  },
  {
    id: "c5",
    name: "Skincare & Beauty",
    slug: "skincare-beauty",
    icon: "✨",
    image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&q=80",
    productCount: 129,
    color: "#ec4899",
    gradient: "linear-gradient(135deg, #ec4899, #f472b6)",
    subcategories: ["Serums", "Moisturizers", "Hair Care", "Sunscreen"],
  },
  {
    id: "c6",
    name: "Essential Oils",
    slug: "essential-oils",
    icon: "🧴",
    image: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400&q=80",
    productCount: 97,
    color: "#8b5cf6",
    gradient: "linear-gradient(135deg, #8b5cf6, #a78bfa)",
    subcategories: ["Lavender", "Peppermint", "Tea Tree", "Diffusers"],
  },
  {
    id: "c7",
    name: "Health Devices",
    slug: "health-devices",
    icon: "🩺",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400&q=80",
    productCount: 68,
    color: "#0ea5e9",
    gradient: "linear-gradient(135deg, #0ea5e9, #38bdf8)",
    subcategories: ["BP Monitors", "Thermometers", "Smart Watches", "Cuffs"],
  },
  {
    id: "c8",
    name: "Personal Care",
    slug: "personal-care",
    icon: "🪥",
    image: "https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?w=400&q=80",
    productCount: 142,
    color: "#f59e0b",
    gradient: "linear-gradient(135deg, #f59e0b, #fbbf24)",
    subcategories: ["Oral Care", "Body Wash", "Deodorants", "Grooming"],
  },
];
// ─────────────────────────────────────────
// PRODUCTS
// ─────────────────────────────────────────
export const products: Product[] = [
  {
    id: "p1",
    name: "Organic Ashwagandha Root Extract",
    slug: "organic-ashwagandha-root-extract",
    description: "Premium KSM-66 Ashwagandha root extract with 5% withanolides. Clinically studied for stress reduction, improved sleep quality, and enhanced physical performance. Third-party tested for purity.",
    shortDescription: "KSM-66 Ashwagandha 500mg | 60 Capsules | Stress Relief & Energy",
    price: 649,
    originalPrice: 999,
    discount: 35,
    rating: 4.8,
    reviewCount: 2341,
    images: [
      "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80",
      "https://images.unsplash.com/photo-1576671081837-49000212a370?w=600&q=80",
    ],
    category: "Herbal & Ayurvedic",
    categorySlug: "herbal-ayurvedic",
    vendor: vendors[2],
    stock: 145,
    tags: ["ashwagandha", "adaptogen", "stress-relief", "ayurvedic"],
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    brand: "AyurVeda Plus",
    sku: "AVP-ASH-001",
    weight: "100g",
    shippingInfo: "Free delivery on orders above ₹499",
  },
  {
    id: "p2",
    name: "Whey Protein Isolate — Chocolate Fudge",
    slug: "whey-protein-isolate-chocolate-fudge",
    description: "25g protein per serving from high-quality whey isolate. Zero sugar, low fat, rich in BCAAs for muscle recovery and growth. Mixes instantly with no clumping.",
    shortDescription: "25g Protein per Serving | 1kg | Zero Sugar | Chocolate Fudge",
    price: 2199,
    originalPrice: 3299,
    discount: 33,
    rating: 4.6,
    reviewCount: 1876,
    images: [
      "https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=600&q=80",
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80",
    ],
    category: "Sports Nutrition",
    categorySlug: "sports-nutrition",
    vendor: vendors[3],
    stock: 89,
    tags: ["whey-protein", "isolate", "chocolate", "muscle-building"],
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    brand: "FitFuel Nutrition",
    sku: "FF-WPI-CHF-1K",
    weight: "1kg",
    shippingInfo: "Free delivery on orders above ₹499",
  },
  {
    id: "p3",
    name: "Vitamin D3 + K2 Complex",
    slug: "vitamin-d3-k2-complex",
    description: "Optimal combination of Vitamin D3 (5000 IU) and Vitamin K2 (MK-7, 100mcg) for superior calcium absorption, bone strength, and cardiovascular health. Sunflower oil-based for better bioavailability.",
    shortDescription: "D3 5000IU + K2 MK-7 100mcg | 120 Softgels | Bone & Heart Health",
    price: 849,
    originalPrice: 1299,
    discount: 35,
    rating: 4.7,
    reviewCount: 3102,
    images: [
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80",
      "https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=600&q=80",
    ],
    category: "Vitamins & Supplements",
    categorySlug: "vitamins-supplements",
    vendor: vendors[1],
    stock: 267,
    tags: ["vitamin-d3", "vitamin-k2", "bone-health", "immunity"],
    isFeatured: true,
    isBestSeller: false,
    isNew: false,
    brand: "VitaLife Labs",
    sku: "VL-D3K2-120",
    weight: "80g",
    shippingInfo: "Free delivery on orders above ₹499",
  },
  {
    id: "p4",
    name: "Cold-Pressed Virgin Coconut Oil",
    slug: "cold-pressed-virgin-coconut-oil",
    description: "Unrefined, cold-pressed coconut oil from fresh coconuts. USDA Organic certified, hexane-free. Perfect for cooking, oil pulling, hair care, and skin moisturizing.",
    shortDescription: "USDA Organic Certified | 500ml | Cold-Pressed | Multi-use",
    price: 449,
    originalPrice: 599,
    discount: 25,
    rating: 4.9,
    reviewCount: 4521,
    images: [
      "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&q=80",
      "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&q=80",
    ],
    category: "Organic Foods",
    categorySlug: "organic-foods",
    vendor: vendors[0],
    stock: 312,
    tags: ["coconut-oil", "organic", "cold-pressed", "cooking"],
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    brand: "NatureRoot Organics",
    sku: "NR-CCO-500",
    weight: "500ml",
    shippingInfo: "Free delivery on orders above ₹499",
  },
  {
    id: "p5",
    name: "Niacinamide 10% + Zinc Serum",
    slug: "niacinamide-10-zinc-serum",
    description: "High-strength niacinamide (10%) paired with zinc PCA (1%) to minimize pores, regulate sebum, brighten skin tone, and reduce blemishes. Lightweight formula, suitable for all skin types.",
    shortDescription: "Niacinamide 10% + Zinc 1% | 30ml | Pore Minimizing Serum",
    price: 399,
    originalPrice: 599,
    discount: 33,
    rating: 4.8,
    reviewCount: 2876,
    images: [
      "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&q=80",
      "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&q=80",
    ],
    category: "Skincare & Beauty",
    categorySlug: "skincare-beauty",
    vendor: vendors[4],
    stock: 198,
    tags: ["niacinamide", "serum", "pore-minimizing", "skincare"],
    isFeatured: true,
    isBestSeller: false,
    isNew: true,
    brand: "PureSkin Wellness",
    sku: "PS-NIA-030",
    weight: "30ml",
    shippingInfo: "Free delivery on orders above ₹499",
  },
  {
    id: "p6",
    name: "Moringa Superfood Powder",
    slug: "moringa-superfood-powder",
    description: "100% pure Moringa leaf powder packed with vitamins, minerals, and antioxidants. Supports immune function, energy levels, and overall wellness. Mixes easily into smoothies and juices.",
    shortDescription: "100% Pure Moringa | 200g | Rich in Antioxidants | USDA Organic",
    price: 349,
    originalPrice: 499,
    discount: 30,
    rating: 4.5,
    reviewCount: 987,
    images: [
      "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=600&q=80",
      "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80",
    ],
    category: "Organic Foods",
    categorySlug: "organic-foods",
    vendor: vendors[0],
    stock: 423,
    tags: ["moringa", "superfood", "antioxidants", "organic"],
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
    brand: "NatureRoot Organics",
    sku: "NR-MOR-200",
    weight: "200g",
    shippingInfo: "Free delivery on orders above ₹499",
  },
  {
    id: "p7",
    name: "Pre-Workout Energy Formula",
    slug: "pre-workout-energy-formula",
    description: "High-stimulant pre-workout with 300mg caffeine, 6g citrulline malate, 3.2g beta-alanine, and elevATP for maximum pump, focus, and endurance. 30 explosive servings.",
    shortDescription: "300mg Caffeine | 30 Servings | Blue Raspberry | Maximum Pump",
    price: 1799,
    originalPrice: 2499,
    discount: 28,
    rating: 4.4,
    reviewCount: 1543,
    images: [
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80",
      "https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=600&q=80",
    ],
    category: "Sports Nutrition",
    categorySlug: "sports-nutrition",
    vendor: vendors[3],
    stock: 76,
    tags: ["pre-workout", "caffeine", "energy", "performance"],
    isFeatured: false,
    isBestSeller: false,
    isNew: true,
    brand: "FitFuel Nutrition",
    sku: "FF-PRE-030",
    weight: "300g",
    shippingInfo: "Free delivery on orders above ₹499",
  },
  {
    id: "p8",
    name: "Omega-3 Fish Oil — Triple Strength",
    slug: "omega-3-fish-oil-triple-strength",
    description: "Pharmaceutical-grade omega-3 from wild-caught deep sea fish. Each softgel delivers 1500mg EPA+DHA for heart health, joint support, and brain function. Molecularly distilled, mercury-tested.",
    shortDescription: "1500mg EPA+DHA | 90 Softgels | Heart & Brain Health | Burpless",
    price: 999,
    originalPrice: 1499,
    discount: 33,
    rating: 4.7,
    reviewCount: 2234,
    images: [
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80",
      "https://images.unsplash.com/photo-1576671081837-49000212a370?w=600&q=80",
    ],
    category: "Vitamins & Supplements",
    categorySlug: "vitamins-supplements",
    vendor: vendors[1],
    stock: 189,
    tags: ["omega-3", "fish-oil", "heart-health", "epa-dha"],
    isFeatured: false,
    isBestSeller: true,
    isNew: false,
    brand: "VitaLife Labs",
    sku: "VL-OMG-090",
    weight: "120g",
    shippingInfo: "Free delivery on orders above ₹499",
  },
  {
    id: "p9",
    name: "Lavender Essential Oil",
    slug: "lavender-essential-oil",
    description: "Pure therapeutic-grade lavender essential oil steam-distilled from Bulgarian lavender fields. Promotes relaxation, better sleep, and calms anxiety. Works in diffusers, topically (diluted), and in baths.",
    shortDescription: "100% Pure | 15ml | Bulgarian Lavender | GC/MS Tested",
    price: 499,
    originalPrice: 799,
    discount: 38,
    rating: 4.9,
    reviewCount: 3456,
    images: [
      "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&q=80",
      "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=600&q=80",
    ],
    category: "Essential Oils",
    categorySlug: "essential-oils",
    vendor: vendors[4],
    stock: 234,
    tags: ["lavender", "essential-oil", "aromatherapy", "sleep"],
    isFeatured: false,
    isBestSeller: true,
    isNew: false,
    brand: "PureSkin Wellness",
    sku: "PS-LAV-015",
    weight: "20g",
    shippingInfo: "Free delivery on orders above ₹499",
  },
  {
    id: "p10",
    name: "Digital Blood Pressure Monitor",
    slug: "digital-blood-pressure-monitor",
    description: "Clinically validated upper arm blood pressure monitor with large LCD display. Stores up to 120 readings for 2 users. Detects irregular heartbeat and displays WHO risk category indicator.",
    shortDescription: "Upper Arm BP Monitor | 120-Reading Memory | Irregular Heartbeat Detection",
    price: 2499,
    originalPrice: 3999,
    discount: 37,
    rating: 4.6,
    reviewCount: 1890,
    images: [
      "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&q=80",
      "https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?w=600&q=80",
    ],
    category: "Health Devices",
    categorySlug: "health-devices",
    vendor: vendors[1],
    stock: 56,
    tags: ["bp-monitor", "blood-pressure", "health-device", "monitoring"],
    isFeatured: true,
    isBestSeller: false,
    isNew: false,
    brand: "VitaLife Labs",
    sku: "VL-BPM-001",
    weight: "350g",
    shippingInfo: "Free delivery on orders above ₹499",
  },
  {
    id: "p11",
    name: "Triphala Churna — Classic Blend",
    slug: "triphala-churna-classic-blend",
    description: "Authentic Triphala powder with equal parts Amalaki, Bibhitaki, and Haritaki. Supports digestive health, detoxification, and gentle cleansing. No additives, fillers, or preservatives.",
    shortDescription: "3-Fruit Ayurvedic Blend | 250g | Digestive Health & Detox",
    price: 249,
    originalPrice: 399,
    discount: 38,
    rating: 4.7,
    reviewCount: 678,
    images: [
      "https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=600&q=80",
      "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=600&q=80",
    ],
    category: "Herbal & Ayurvedic",
    categorySlug: "herbal-ayurvedic",
    vendor: vendors[2],
    stock: 521,
    tags: ["triphala", "ayurvedic", "digestive", "detox"],
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
    brand: "AyurVeda Plus",
    sku: "AVP-TRP-250",
    weight: "250g",
    shippingInfo: "Free delivery on orders above ₹499",
  },
  {
    id: "p12",
    name: "Biotin Hair Growth Gummies",
    slug: "biotin-hair-growth-gummies",
    description: "Delicious strawberry gummies with 10,000mcg Biotin plus Folic Acid, Vitamin B12, and Zinc for stronger hair and faster growth. Vegan, gluten-free, no artificial colors.",
    shortDescription: "10,000mcg Biotin | 60 Gummies | Strawberry Flavor | Vegan",
    price: 699,
    originalPrice: 999,
    discount: 30,
    rating: 4.5,
    reviewCount: 1234,
    images: [
      "https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?w=600&q=80",
      "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&q=80",
    ],
    category: "Personal Care",
    categorySlug: "personal-care",
    vendor: vendors[4],
    stock: 167,
    tags: ["biotin", "hair-growth", "gummies", "vitamins"],
    isFeatured: false,
    isBestSeller: false,
    isNew: true,
    brand: "PureSkin Wellness",
    sku: "PS-BIO-060",
    weight: "200g",
    shippingInfo: "Free delivery on orders above ₹499",
  },
];

// ─────────────────────────────────────────
// HERO SLIDES
// ─────────────────────────────────────────
export const heroSlides: HeroSlide[] = [
  {
    id: "h1",
    title: "Your Health,\nOur Priority",
    subtitle: "Discover 1,000+ premium health products from verified vendors. Organic, authentic, and delivered to your door.",
    cta: "Shop Now",
    ctaLink: "/products",
    image: "https://images.unsplash.com/photo-1576671081837-49000212a370?w=1200&q=80",
    bgColor: "from-[#1E1E1E] to-[#2a2a2a]",
    badge: "⚡ Flash Sale — Up to 40% Off",
  },
  {
    id: "h2",
    title: "Pure &\nOrganic",
    subtitle: "Explore our curated range of certified organic supplements, superfoods, and herbal extracts.",
    cta: "Explore Organics",
    ctaLink: "/products?category=organic-foods",
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=1200&q=80",
    bgColor: "from-[#1a2e00] to-[#2d4d00]",
    badge: "🌿 100% Organic Certified",
  },
  {
    id: "h3",
    title: "Fuel Your\nPerformance",
    subtitle: "Science-backed sports nutrition to help you train harder, recover faster, and achieve your fitness goals.",
    cta: "Shop Sports Nutrition",
    ctaLink: "/products?category=sports-nutrition",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=1200&q=80",
    bgColor: "from-[#3d1a00] to-[#5a2600]",
    badge: "💪 Top-Rated Athletes' Choice",
  },
];

// ─────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────
export const getFeaturedProducts = () => products.filter((p) => p.isFeatured);
export const getBestSellers = () => products.filter((p) => p.isBestSeller);
export const getNewArrivals = () => products.filter((p) => p.isNew);
export const getProductBySlug = (slug: string) => products.find((p) => p.slug === slug);
export const getProductsByCategory = (slug: string) =>
  products.filter((p) => p.categorySlug === slug);
export const getRelatedProducts = (product: Product) =>
  products
    .filter((p) => p.categorySlug === product.categorySlug && p.id !== product.id)
    .slice(0, 4);
